-- DLavie Community v89: owner role, scoped staff roles, settings, forum visibility, pins, and audit log.
alter table public.dlavie_community_roles add column if not exists scope jsonb not null default '[]'::jsonb;
alter table public.dlavie_community_roles add column if not exists protected boolean not null default false;
alter table public.dlavie_community_roles add column if not exists role_kind text not null default 'identity';

do $$ begin
  if not exists (select 1 from pg_constraint where conname='dlavie_community_roles_role_kind_check') then
    alter table public.dlavie_community_roles add constraint dlavie_community_roles_role_kind_check check (role_kind in ('identity','staff','custom'));
  end if;
end $$;

alter table public.dlavie_community_messages add column if not exists pinned_at timestamptz;
alter table public.dlavie_community_messages add column if not exists pinned_by uuid references public.dlavie_community_members(id) on delete set null;
alter table public.dlavie_community_messages add column if not exists pinned_reason text not null default '';

create table if not exists public.dlavie_community_settings (
  id smallint primary key default 1 check (id=1),
  community_name text not null default 'DLavie Hub',
  community_tagline text not null default 'Tempat ngobrol, minta bantuan, berbagi karya, dan ikut menentukan arah DLavie.',
  welcome_title text not null default 'Selamat datang di DLavie Community',
  welcome_body text not null default 'Chat publik DLavie untuk ngobrol, bantuan, showcase, feedback, voting, dan komunitas.',
  rules_intro text not null default 'Baca seluruh aturan, pahami setiap poin, lalu verifikasi Community Passport untuk membuka fitur komunitas.',
  support_text text not null default 'Gunakan Report untuk pelanggaran dan #help untuk bantuan.',
  updated_at timestamptz not null default now(),
  updated_by uuid references public.dlavie_community_members(id) on delete set null
);
insert into public.dlavie_community_settings(id) values(1) on conflict (id) do nothing;

create table if not exists public.dlavie_community_forum_settings (
  kind text primary key check (kind in ('feedback','vote','report')),
  visibility text not null default 'public' check (visibility in ('public','private')),
  posting_enabled boolean not null default true,
  title_override text not null default '',
  description_override text not null default '',
  updated_at timestamptz not null default now(),
  updated_by uuid references public.dlavie_community_members(id) on delete set null
);
insert into public.dlavie_community_forum_settings(kind,visibility,posting_enabled) values
 ('feedback','public',true),('vote','public',true),('report','private',true)
on conflict (kind) do nothing;

create table if not exists public.dlavie_community_admin_audit (
  id bigint generated by default as identity primary key,
  actor_member_id uuid references public.dlavie_community_members(id) on delete set null,
  action text not null,
  target_type text not null default '',
  target_id text not null default '',
  details jsonb not null default '{}'::jsonb,
  created_at timestamptz not null default now()
);
create index if not exists dlavie_community_admin_audit_created_at_idx on public.dlavie_community_admin_audit(created_at desc);
create index if not exists dlavie_community_messages_pinned_idx on public.dlavie_community_messages(channel_id,pinned_at desc) where pinned_at is not null and deleted_at is null;

insert into public.dlavie_community_roles(slug,name,description,icon,color,self_assignable,sort_order,scope,protected,role_kind)
values
 ('owner','Owner','Pemilik DLavie Community dengan akses penuh.','crown','#f4c95d',false,-100,'["community.manage","settings.edit","roles.manage","roles.assign","channels.manage","messages.delete","messages.pin","forums.manage","moderation.manage","rules.manage","members.manage","audit.view"]'::jsonb,true,'staff'),
 ('admin','Admin','Mengelola komunitas, role, forum, dan moderasi.','shield','#70d7ff',false,-90,'["settings.edit","roles.manage","roles.assign","channels.manage","messages.delete","messages.pin","forums.manage","moderation.manage","rules.manage","members.manage","audit.view"]'::jsonb,true,'staff'),
 ('moderator','Moderator','Menjaga chat, pin pesan, forum, dan menangani moderasi.','shield-check','#65df93',false,-80,'["messages.delete","messages.pin","forums.manage","moderation.manage"]'::jsonb,true,'staff'),
 ('developer','Developer','Role internal developer DLavie dengan akses konfigurasi teknis komunitas.','code','#b793ff',false,-70,'["settings.edit","channels.manage","audit.view"]'::jsonb,true,'staff')
on conflict (slug) do update set
 name=excluded.name,description=excluded.description,icon=excluded.icon,color=excluded.color,
 self_assignable=false,scope=excluded.scope,protected=true,role_kind='staff';

update public.dlavie_community_members m
set role='owner'
where m.id=(select a.member_id from public.dlavie_accounts a join auth.users u on u.id=a.user_id where lower(u.email)=lower('dlaviecom@gmail.com') limit 1);

insert into public.dlavie_community_member_roles(member_id,role_id)
select a.member_id,r.id
from public.dlavie_accounts a
join auth.users u on u.id=a.user_id
join public.dlavie_community_roles r on r.slug='owner'
where lower(u.email)=lower('dlaviecom@gmail.com') and a.member_id is not null
on conflict do nothing;

create or replace function public.dlavie_community_forum_posting_guard()
returns trigger
language plpgsql
security definer
set search_path=public
as $$
declare enabled boolean;
begin
  select posting_enabled into enabled from public.dlavie_community_forum_settings where kind=new.kind;
  if enabled is false then
    raise exception 'Posting untuk forum % sedang dinonaktifkan.', new.kind using errcode='P0001';
  end if;
  return new;
end;
$$;

drop trigger if exists dlavie_community_forum_posting_guard_trg on public.dlavie_community_forum_posts;
create trigger dlavie_community_forum_posting_guard_trg
before insert on public.dlavie_community_forum_posts
for each row execute function public.dlavie_community_forum_posting_guard();
